# Generated by Django 2.2.12 on 2020-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_type', models.CharField(choices=[('technical', 'TECHNICAL'), ('other', 'OTHER')], default='technical', max_length=10)),
            ],
        ),
    ]
